"""Doris column definitions for the normalized DWARF record families."""

from __future__ import annotations

_VALUE_COLUMNS = (
    "raw_value_kind VARCHAR(32)",
    "raw_value_bool BOOLEAN",
    "raw_value_int BIGINT",
    "raw_value_uint LARGEINT",
    "raw_value_float DOUBLE",
    "raw_value_text STRING",
    "raw_value_binary STRING",
    "raw_value_json STRING",
    "raw_value_path VARCHAR(512)",
    "raw_value_sha256 CHAR(64)",
    "raw_value_size LARGEINT",
    "decoded_value_kind VARCHAR(32)",
    "decoded_value_bool BOOLEAN",
    "decoded_value_int BIGINT",
    "decoded_value_uint LARGEINT",
    "decoded_value_float DOUBLE",
    "decoded_value_text STRING",
    "decoded_value_binary STRING",
    "decoded_value_json STRING",
    "decoded_value_path VARCHAR(512)",
    "decoded_value_sha256 CHAR(64)",
    "decoded_value_size LARGEINT",
)

_TARGET_COLUMNS = (
    "raw_target_kind VARCHAR(32)",
    "raw_target_bool BOOLEAN",
    "raw_target_int BIGINT",
    "raw_target_uint LARGEINT",
    "raw_target_float DOUBLE",
    "raw_target_text STRING",
    "raw_target_binary STRING",
    "raw_target_json STRING",
    "raw_target_path VARCHAR(512)",
    "raw_target_sha256 CHAR(64)",
    "raw_target_size LARGEINT",
)

_FAMILY_COLUMNS: dict[str, tuple[str, ...]] = {
    "section": (
        "section_index BIGINT NOT NULL",
        "source_id CHAR(64) NOT NULL",
        "record_type VARCHAR(32) NOT NULL",
        "section_name VARCHAR(128)",
        "file_offset BIGINT",
        "file_size BIGINT",
        "raw_path VARCHAR(512)",
        "raw_sha256 CHAR(64)",
        "chunk_size BIGINT",
        "chunk_count BIGINT",
    ),
    "raw_chunk": (
        "section_index BIGINT NOT NULL",
        "chunk_index BIGINT NOT NULL",
        "source_id CHAR(64) NOT NULL",
        "record_type VARCHAR(32) NOT NULL",
        "section_name VARCHAR(128)",
        "raw_path VARCHAR(512)",
        "byte_offset BIGINT",
        "byte_size BIGINT",
        "file_offset BIGINT",
        "raw_sha256 CHAR(64)",
    ),
    "unit": (
        "unit_offset BIGINT NOT NULL",
        "source_id CHAR(64) NOT NULL",
        "record_type VARCHAR(32) NOT NULL",
        "unit_bucket BIGINT",
        "unit_length BIGINT",
        "unit_type VARCHAR(64)",
        "header_json STRING",
        "parser_status VARCHAR(32)",
        "details_json STRING",
    ),
    "die": (
        "unit_offset BIGINT NOT NULL",
        "die_offset BIGINT NOT NULL",
        "ordinal BIGINT NOT NULL",
        "source_id CHAR(64) NOT NULL",
        "record_type VARCHAR(32) NOT NULL",
        "unit_bucket BIGINT",
        "tag VARCHAR(128)",
        "abbrev_code BIGINT",
        "has_children BOOLEAN",
        "depth INT",
        "parent_offset BIGINT",
        "is_null BOOLEAN",
    ),
    "attribute": (
        "unit_offset BIGINT NOT NULL",
        "die_offset BIGINT NOT NULL",
        "ordinal BIGINT NOT NULL",
        "source_id CHAR(64) NOT NULL",
        "record_type VARCHAR(32) NOT NULL",
        "unit_bucket BIGINT",
        "name VARCHAR(128)",
        "form VARCHAR(64)",
        "value_offset BIGINT",
        "indirection_length BIGINT",
        *_VALUE_COLUMNS,
    ),
    "reference": (
        "unit_offset BIGINT NOT NULL",
        "die_offset BIGINT NOT NULL",
        "attribute_name VARCHAR(128) NOT NULL",
        "relation VARCHAR(64) NOT NULL",
        "source_id CHAR(64) NOT NULL",
        "record_type VARCHAR(32) NOT NULL",
        "unit_bucket BIGINT",
        *_TARGET_COLUMNS,
        "target_offset BIGINT",
        "resolution_status VARCHAR(32)",
    ),
    "index": (
        "unit_offset BIGINT NOT NULL",
        "die_offset BIGINT NOT NULL",
        "index_type VARCHAR(64) NOT NULL",
        "source_id CHAR(64) NOT NULL",
        "record_type VARCHAR(32) NOT NULL",
        "unit_bucket BIGINT",
        "name VARCHAR(1024)",
        "tag VARCHAR(128)",
        *_TARGET_COLUMNS,
        "target_offset BIGINT",
        "resolution_status VARCHAR(32)",
    ),
    "range": (
        "unit_offset BIGINT NOT NULL",
        "die_offset BIGINT NOT NULL",
        "ordinal BIGINT NOT NULL",
        "source_id CHAR(64) NOT NULL",
        "record_type VARCHAR(32) NOT NULL",
        "unit_bucket BIGINT",
        "attribute_name VARCHAR(128)",
        "record_offset BIGINT",
        "record_length BIGINT",
        "entry_kind VARCHAR(64)",
        "parser_status VARCHAR(32)",
        "details_json STRING",
        "start_address LARGEINT",
        "end_address LARGEINT",
        "base_address LARGEINT",
        "is_absolute BOOLEAN",
    ),
    "location": (
        "unit_offset BIGINT NOT NULL",
        "die_offset BIGINT NOT NULL",
        "ordinal BIGINT NOT NULL",
        "source_id CHAR(64) NOT NULL",
        "record_type VARCHAR(32) NOT NULL",
        "unit_bucket BIGINT",
        "attribute_name VARCHAR(128)",
        "record_offset BIGINT",
        "record_length BIGINT",
        "entry_kind VARCHAR(64)",
        "parser_status VARCHAR(32)",
        "details_json STRING",
        "start_address LARGEINT",
        "end_address LARGEINT",
        "is_absolute BOOLEAN",
        "expression_json STRING",
    ),
    "line": (
        "unit_offset BIGINT NOT NULL",
        "ordinal BIGINT NOT NULL",
        "source_id CHAR(64) NOT NULL",
        "record_type VARCHAR(32) NOT NULL",
        "unit_bucket BIGINT",
        "entry_kind VARCHAR(32)",
        "program_offset BIGINT",
        "record_offset BIGINT",
        "command BIGINT",
        "address LARGEINT",
        "file_index BIGINT",
        "directory_index BIGINT",
        "source_file VARCHAR(1024)",
        "directory VARCHAR(1024)",
        "line BIGINT",
        "`column` BIGINT",
        "op_index BIGINT",
        "is_stmt BOOLEAN",
        "basic_block BOOLEAN",
        "end_sequence BOOLEAN",
        "prologue_end BOOLEAN",
        "epilogue_begin BOOLEAN",
        "isa BIGINT",
        "discriminator BIGINT",
        "details_json STRING",
    ),
    "macro": (
        "section_name VARCHAR(128) NOT NULL",
        "record_offset BIGINT NOT NULL",
        "source_id CHAR(64) NOT NULL",
        "record_type VARCHAR(32) NOT NULL",
        "record_length BIGINT",
        "macro_kind VARCHAR(64)",
        "raw_path VARCHAR(512)",
        "raw_sha256 CHAR(64)",
        "parser_status VARCHAR(32)",
        "details_json STRING",
    ),
    "frame": (
        "section_name VARCHAR(128) NOT NULL",
        "record_offset BIGINT NOT NULL",
        "source_id CHAR(64) NOT NULL",
        "record_type VARCHAR(32) NOT NULL",
        "record_length BIGINT",
        "frame_kind VARCHAR(64)",
        "initial_address LARGEINT",
        "address_range LARGEINT",
        "parser_status VARCHAR(32)",
        "details_json STRING",
    ),
    "abbreviation": (
        "unit_offset BIGINT NOT NULL",
        "abbrev_code BIGINT NOT NULL",
        "source_id CHAR(64) NOT NULL",
        "record_type VARCHAR(32) NOT NULL",
        "unit_bucket BIGINT",
        "record_offset BIGINT",
        "tag VARCHAR(128)",
        "has_children BOOLEAN",
        "parser_status VARCHAR(32)",
        "details_json STRING",
    ),
    "name": (
        "unit_offset BIGINT NOT NULL",
        "die_offset BIGINT NOT NULL",
        "ordinal BIGINT NOT NULL",
        "source_id CHAR(64) NOT NULL",
        "record_type VARCHAR(32) NOT NULL",
        "unit_bucket BIGINT",
        "name VARCHAR(1024)",
        "name_kind VARCHAR(64)",
        "attribute_name VARCHAR(128)",
        "parser_status VARCHAR(32)",
        "details_json STRING",
    ),
}
