name: ddon-analytical-dwarf

networks:
  default:
    ipam:
      config:
        - subnet: 172.31.240.0/24

services:
  doris-fe:
    image: apache/doris:fe-4.1.3@sha256:3dd47644cd9fa8152028bdae449e77170ab0de004bd7a3fa311a204a106c26c7
    hostname: fe
    environment:
      FE_SERVERS: fe1:172.31.240.2:9010
      FE_ID: "1"
    networks:
      default:
        ipv4_address: 172.31.240.2
    ports:
      - "8030:8030"
      - "9030:9030"
    volumes:
      - ${DDON_DORIS_FE_DATA:-../../output/analytical-dwarf/warehouse/doris-fe-4.1.3}:/opt/apache-doris/fe/doris-meta
      - ${DDON_DORIS_FE_LOG:-../../output/analytical-dwarf/warehouse/doris-fe-4.1.3-log}:/opt/apache-doris/fe/log
      - ${DDON_DORIS_STORE_HOST_PATH:-../../output/analytical-dwarf/main}:/opt/analytical:ro

  doris-be:
    image: apache/doris:be-4.1.3@sha256:9f84a8b018069cd3c9a65af42ff5ef2c733b3b25e1ca708e0a3e4078361a1eb3
    hostname: be
    depends_on:
      - doris-fe
    environment:
      FE_SERVERS: fe1:172.31.240.2:9010
      BE_ADDR: 172.31.240.3:9050
    networks:
      default:
        ipv4_address: 172.31.240.3
    ports:
      - "8040:8040"
    volumes:
      - ${DDON_DORIS_BE_DATA:-../../output/analytical-dwarf/warehouse/doris-be-4.1.3}:/opt/apache-doris/be/storage
      - ${DDON_DORIS_BE_LOG:-../../output/analytical-dwarf/warehouse/doris-be-4.1.3-log}:/opt/apache-doris/be/log
      - ${DDON_DORIS_STORE_HOST_PATH:-../../output/analytical-dwarf/main}:/opt/analytical:ro
