name: Code Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-type-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
        
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
        
    - name: Install dependencies
      run: |
        uv venv
        uv pip install -e ".[dev]"
        
    - name: Run ruff linter
      run: |
        uv run ruff check src/ tests/ --output-format=github
        
    - name: Run ruff formatter check
      run: |
        uv run ruff format src/ tests/ --check --diff
        
    - name: Run mypy type checker
      run: |
        uv run mypy src/