name: Unit Tests and Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.13']
    
    steps:
    - name: Check out code
      uses: actions/checkout@v4
      
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
        
    - name: Install dependencies
      run: |
        uv venv
        uv pip install -e ".[dev]"
        
    - name: Run unit tests with coverage
      run: |
        uv run pytest -m "unit" --cov-fail-under=30
        
    - name: Generate coverage report
      run: |
        uv run coverage report --show-missing
        
    - name: Upload coverage reports to Codecov
      if: matrix.python-version == '3.13'
      uses: codecov/codecov-action@v4
      with:
        files: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
        
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results-${{ matrix.python-version }}
        path: |
          test-results.xml
          coverage.xml
          htmlcov/
        retention-days: 30
        
    - name: Publish test results
      if: always() && matrix.python-version == '3.13'
      uses: EnricoMi/publish-unit-test-result-action@v2
      with:
        files: test-results.xml
        check_name: "Unit Test Results (Python ${{ matrix.python-version }})"