name: Unit Tests and Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
        
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
        
    - name: Install dependencies
      run: |
        uv venv
        uv pip install -e ".[dev]"
        
    - name: Run unit tests with coverage
      run: |
        uv run pytest -m "unit" --cov=src --cov-fail-under=30 --cov-report=xml --cov-report=html --junit-xml=test-results.xml
        
    - name: Generate coverage report
      run: |
        uv run coverage report --show-missing
        
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
      with:
        files: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
        
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          test-results.xml
          coverage.xml
          htmlcov/
        retention-days: 30
        
    - name: Publish test results
      if: always()
      uses: EnricoMi/publish-unit-test-result-action@v2
      continue-on-error: true
      with:
        files: test-results.xml
        check_name: "Unit Test Results"